services:
    cla-postgresql-db:
        container_name: cla-db-dev
        image: postgres:latest
        hostname: localhost
        ports:
            - "5432:5432"
        env_file: .env
        volumes:
            - ./.postgres/data:/var/lib/postgresql/data
